### ISSUE TITLE
Enums Not Importing Correctly

### ISSUE THREAD

**Issue by mtskillman** [MaxBittker/orb.farm#10]
After cloning project, installing Rust and running npm install, then npm start, app will be inoperable due to `import { Species } from "../crate/pkg/sandtable";` returning an object rather than an enum (i'm not familiar enough with these languages to express this correctly). Functions utilizing this enum will then receive strings as arguments, when they only accept numbers. 

line 235 in js/render.js:
![code1](https://user-images.githubusercontent.com/55630669/92816053-f0443c80-f392-11ea-88b1-bb69510ee103.PNG)

error and result of printing to console:
![code2](https://user-images.githubusercontent.com/55630669/92816087-0520d000-f393-11ea-906c-a4d20a3eb716.PNG)

contents of Species in js/render.js:
![code3](https://user-images.githubusercontent.com/55630669/92816163-1cf85400-f393-11ea-8288-4b3b242756b4.PNG)

 

node v12.18.3
rustc 1.46.0
npm 6.14.6
using WSL 1 with Windows 10

**Comment by abend** [comment]
Hi. I have a quick fix for this as PR #11. See if it works for you.

**Comment by mtskillman** [comment]
> Hi. I have a quick fix for this as PR #11. See if it works for you.

thanks! i'll take a look

**Comment by mtskillman** [comment]
this pr should do the trick:
https://github.com/MaxBittker/orb.farm/pull/12

**Comment by MaxBittker** [comment]
thanks both :)
