### ISSUE TITLE
Clear button is evading mouse clicks

### ISSUE THREAD

**Issue by mootari** [MaxBittker/orb.farm#3]
Apparently the Clear button doesn't like to be toggled:
1. Mousedown on the clear button triggers a layout change that causes the button to move away from the cursor position.
2. On mouseup the button is no longer below the mouse and won't become selected.

Browser: Chrome 81 on MacOS 10.13.6

Demo (including a workaround):

![Kapture 2020-05-17 at 21 46 58](https://user-images.githubusercontent.com/322014/82158403-f6645980-9887-11ea-8518-8d6d2a65fa71.gif)

**Comment by MaxBittker** [comment]
:D :see_no_evil:  oh jeeze I'm getting it too. maybe the solution is a box-sizing change?

**Comment by mootari** [comment]
Found it! The cause is a different padding for `button:not(:disabled):active`.

**Comment by MaxBittker** [comment]
thank you for the catch. I pushed a fix! 

```
button:not(:disabled):active {
  padding: 1px 5px !important;
}
```

box sizing didn't seem to work when i tried it

**Comment by mootari** [comment]
> box sizing didn't seem to work when i tried it

Yup, my bad, still had the padding rule disabled when I tested that. `border-box` already gets applied at multiple levels. I shouldn't try to multitask ...
