### ISSUE TITLE
Menu buttons inaccessible at 1015px width

### ISSUE THREAD

**Issue by mootari** [MaxBittker/orb.farm#4]
At around >=1015px the menu switches to a narrow layout that forces its buttons into a single column. Unfortunately, because the menu is too narrow the buttons to become inaccessible.

![image](https://user-images.githubusercontent.com/322014/82158702-bdc57f80-9889-11ea-9bf6-7e1881705f36.png)

**Comment by mootari** [comment]
I believe you can get rid of the HUDStyle changes in JS and achieve better control through CSS + media queries + calc() (if necessary).

What is the intent of that layout change? Do you want to display the buttons vertically whenever possible? because it could be argued that this could be done at far narrower widths.

**Comment by MaxBittker** [comment]
![image](https://user-images.githubusercontent.com/5915546/82833508-274a1d00-9e8c-11ea-9b25-be334323d3e2.png)

I patched this issues with another piece of JS cludge :sweat_smile: 

I agree that there might be a better way to get this to flow between different layouts in CSS, but I'm not sure exactly what I even want it to look like so I'm decently happy with the current behavior. (kind of wish the buttons wrapped around the gauge more nicely.)

thanks for opening the issue Fabian!
