### ISSUE TITLE
please add a pause button

### ISSUE THREAD

**Issue by emberian** [MaxBittker/orb.farm#5]
i can't get out of my chair to sustain my own life at the cost of my orb denizens.

**Comment by emberian** [comment]
identified workaround: knock out the bottom of the orb, drain the denizens into the abyss, no more existential dread.

**Comment by MaxBittker** [comment]
:) you can close the tab and it saves! I wanted to have less UI , the pause button from sandspiel is still in the code but i'm keeping it commented out for now

**Comment by emberian** [comment]
i drained my orb for naught!
